services:
  - type: web
    name: proyecto-fono
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgres://fono_p_user:1Syqy6rHJmOUa9r4m7EMduCRAED4bYFK@dpg-d137jvc9c44c739052b0-a.oregon-postgres.render.com:5432/fono_p"
    autoDeploy: true
