services:
  - type: web
    name: proyecto-fono
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true